export const COLOR_PALETTE = [
  { name: "Black", color: "#000000" },
  { name: "Dark Gray", color: "#3C3C3C" },
  { name: "Gray", color: "#787878" },
  { name: "Light Gray", color: "#D2D2D2" },
  { name: "White", color: "#FFFFFF" },
  { name: "Deep Red", color: "#600018" },
  { name: "Red", color: "#ED1C24" },
  { name: "Orange", color: "#FF7F27" },
  { name: "Gold", color: "#F6AA09" },
  { name: "Yellow", color: "#F9DD3B" },
  { name: "Light Yellow", color: "#FFFABC" },
  { name: "Dark Green", color: "#0EB968" },
  { name: "Green", color: "#13E67B" },
  { name: "Light Green", color: "#87FF5E" },
  { name: "Dark Teal", color: "#0C816E" },
  { name: "Teal", color: "#10AE82" },
  { name: "Light Teal", color: "#13E1BE" },
  { name: "Cyan", color: "#60F7F2" },
  { name: "Dark Blue", color: "#28509E" },
  { name: "Blue", color: "#4093E4" },
  { name: "Indigo", color: "#6B50F6" },
  { name: "Light Indigo", color: "#99B1FB" },
  { name: "Dark Purple", color: "#780C99" },
  { name: "Purple", color: "#AA38B9" },
  { name: "Light Purple", color: "#E09FF9" },
  { name: "Dark Pink", color: "#CB007A" },
  { name: "Pink", color: "#EC1F80" },
  { name: "Light Pink", color: "#F38DA9" },
  { name: "Dark Brown", color: "#684634" },
  { name: "Brown", color: "#95682A" },
  { name: "Beige", color: "#F8B277" },
  { name: "Medium Gray", color: "#AAAAAA" },
  { name: "Dark Red", color: "#A50E1E" },
  { name: "Light Red", color: "#FA8072" },
  { name: "Dark Orange", color: "#E45C1A" },
  { name: "Dark Goldenrod", color: "#9C8431" },
  { name: "Goldenrod", color: "#C5AD31" },
  { name: "Light Goldenrod", color: "#E8D45F" },
  { name: "Dark Olive", color: "#4A6B3A" },
  { name: "Olive", color: "#5A944A" },
  { name: "Light Olive", color: "#84C573" },
  { name: "Dark Cyan", color: "#0F799F" },
  { name: "Light Cyan", color: "#BBFAF2" },
  { name: "Light Blue", color: "#7DC7FF" },
  { name: "Dark Indigo", color: "#4D31B8" },
  { name: "Dark Slate Blue", color: "#4A4284" },
  { name: "Slate Blue", color: "#7A71C4" },
  { name: "Light Slate Blue", color: "#B5AEF1" },
  { name: "Dark Peach", color: "#9B5249" },
  { name: "Peach", color: "#D18078" },
  { name: "Light Peach", color: "#FAB6A4" },
  { name: "Light Brown", color: "#DBA463" },
  { name: "Dark Tan", color: "#7B6352" },
  { name: "Tan", color: "#9C846B" },
  { name: "Light Tan", color: "#D6B594" },
  { name: "Dark Beige", color: "#D18051" },
  { name: "Light Beige", color: "#FFC5A5" },
  { name: "Dark Stone", color: "#6D643F" },
  { name: "Stone", color: "#948C6B" },
  { name: "Light Stone", color: "#CDC59E" },
  { name: "Dark Slate", color: "#333941" },
  { name: "Slate", color: "#6D758D" },
  { name: "Light Slate", color: "#B3B9D1" }
];
