export const COLOR_PALETTE = [
  { name: "Wplace Black", color: "#000000" },
  { name: "Wplace Dark Gray", color: "#3C3C3C" },
  { name: "Wplace Gray", color: "#787878" },
  { name: "Wplace Light Gray", color: "#D2D2D2" },
  { name: "Wplace White", color: "#FFFFFF" },
  { name: "Wplace Deep Red", color: "#600018" },
  { name: "Wplace Red", color: "#ED1C24" },
  { name: "Wplace Orange", color: "#FF7F27" },
  { name: "Wplace Gold", color: "#F6AA09" },
  { name: "Wplace Yellow", color: "#F9DD3B" },
  { name: "Wplace Light Yellow", color: "#FFFABC" },
  { name: "Wplace Dark Green", color: "#0EB968" },
  { name: "Wplace Green", color: "#13E67B" },
  { name: "Wplace Light Green", color: "#87FF5E" },
  { name: "Wplace Dark Teal", color: "#0C816E" },
  { name: "Wplace Teal", color: "#10AE82" },
  { name: "Wplace Light Teal", color: "#13E1BE" },
  { name: "Wplace Cyan", color: "#60F7F2" },
  { name: "Wplace Dark Blue", color: "#28509E" },
  { name: "Wplace Blue", color: "#4093E4" },
  { name: "Wplace Indigo", color: "#6B50F6" },
  { name: "Wplace Light Indigo", color: "#99B1FB" },
  { name: "Wplace Dark Purple", color: "#780C99" },
  { name: "Wplace Purple", color: "#AA38B9" },
  { name: "Wplace Light Purple", color: "#E09FF9" },
  { name: "Wplace Dark Pink", color: "#CB007A" },
  { name: "Wplace Pink", color: "#EC1F80" },
  { name: "Wplace Light Pink", color: "#F38DA9" },
  { name: "Wplace Dark Brown", color: "#684634" },
  { name: "Wplace Brown", color: "#95682A" },
  { name: "Wplace Beige", color: "#F8B277" },
  { name: "Wplace Medium Gray", color: "#AAAAAA" },
  { name: "Wplace Dark Red", color: "#A50E1E" },
  { name: "Wplace Light Red", color: "#FA8072" },
  { name: "Wplace Dark Orange", color: "#E45C1A" },
  { name: "Wplace Dark Goldenrod", color: "#9C8431" },
  { name: "Wplace Goldenrod", color: "#C5AD31" },
  { name: "Wplace Light Goldenrod", color: "#E8D45F" },
  { name: "Wplace Dark Olive", color: "#4A6B3A" },
  { name: "Wplace Olive", color: "#5A944A" },
  { name: "Wplace Light Olive", color: "#84C573" },
  { name: "Wplace Dark Cyan", color: "#0F799F" },
  { name: "Wplace Light Cyan", color: "#BBFAF2" },
  { name: "Wplace Light Blue", color: "#7DC7FF" },
  { name: "Wplace Dark Indigo", color: "#4D31B8" },
  { name: "Wplace Dark Slate Blue", color: "#4A4284" },
  { name: "Wplace Slate Blue", color: "#7A71C4" },
  { name: "Wplace Light Slate Blue", color: "#B5AEF1" },
  { name: "Wplace Dark Peach", color: "#9B5249" },
  { name: "Wplace Peach", color: "#D18078" },
  { name: "Wplace Light Peach", color: "#FAB6A4" },
  { name: "Wplace Light Brown", color: "#DBA463" },
  { name: "Wplace Dark Tan", color: "#7B6352" },
  { name: "Wplace Tan", color: "#9C846B" },
  { name: "Wplace Light Tan", color: "#D6B594" },
  { name: "Wplace Dark Beige", color: "#D18051" },
  { name: "Wplace Light Beige", color: "#FFC5A5" },
  { name: "Wplace Dark Stone", color: "#6D643F" },
  { name: "Wplace Stone", color: "#948C6B" },
  { name: "Wplace Light Stone", color: "#CDC59E" },
  { name: "Wplace Dark Slate", color: "#333941" },
  { name: "Wplace Slate", color: "#6D758D" },
  { name: "Wplace Light Slate", color: "#B3B9D1" }
];
